server:
  port: 8080

#langchain4j.open-ai.chat-model:
#  api-key: ${API_KEY_ECNU_CHAT}
#  model-name: ecnu-reasoner
#  # 应用程序发送给大模型的请求日志和相应日志
#  log-requests: true
#  log-responses: true
#  base-url: https://chat.ecnu.edu.cn/open/api/v1/
#


langchain4j.community.dashscope:
  chat-model:
    api-key: ${API_KEY_ALI_BAILIAN}
    model-name: qwen-flash
  embedding-model:
    api-key: ${API_KEY_ALI_BAILIAN}
    model-name: text-embedding-v3

#MongoDB连接配置
spring.data.mongodb.uri: mongodb://172.30.138.31:27017/chat_memory_db
logging:
  level:
    root: info

# 基本数据源配置
spring.datasource:
  url: jdbc:mysql://localhost:3306/guigu_xiaozhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver
# 开启 SQL 日志打印
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl